image: Visual Studio 2017
version: 4.15.0-alpha-{build}
configuration: Release
environment:
  ZendeskApi_Credentials_Url:
    secure: C2FCZYsQc4saCFZ4Uw6gkBqHoyXZPsKucJRXKGKBhYp9cBxCXxupzuo9jB0ftVah
  ZendeskApi_Credentials_Username: 
    secure: ft+ZIlhKYIHzQ+0Phrool1mjCK1QksYDv6hWtq/pPP0=
  ZendeskApi_Credentials_Token: 
    secure: GRSdM9G3MmHr5PymLoHbtyU2sD7/pz/tv4FUlt2JY3zZm7OYBR1zFT6pmusYiRjx
before_build:
  - dotnet restore
build:
  project: ZendeskApiClient.sln
  parallel: true
  verbosity: minimal
clone_depth: 1
test_script:
- dotnet test -c Release .\test\ZendeskApi.Client.Tests\ZendeskApi.Client.Tests.csproj
after_build:
- dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
artifacts:
- path: 'output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: ZkYI4stkqiH2+3Y5u4kv6/WEbVpiyoQSSXp5is3ODPxlYu1uMdnkK1dDgfTSH4VG
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
for:
-
  branches:
    only:
      - master
  test_script:
    - dotnet test -c Release .\test\ZendeskApi.Client.IntegrationTests\ZendeskApi.Client.IntegrationTests.csproj
