image: Visual Studio 2017
version: 3.8.0-alpha-{build}
configuration: Release
before_build:
  - dotnet restore
build:
  project: ZendeskApiClient.sln
  parallel: true
  verbosity: minimal
clone_depth: 1
test_script:
- dotnet test -c Release .\test\ZendeskApi.Client.Tests\ZendeskApi.Client.Tests.csproj
after_build:
- dotnet pack .\src\ZendeskApi.Client\ZendeskApi.Client.csproj -o ../../output --no-build
artifacts:
- path: 'output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
